export {
  normalizeSnapshot,
  fetchFinanceSnapshot,
  allocationSlices,
  type FinanceSnapshot,
  type RawLuminaSnapshot,
  type AllocationSlice,
} from './snapshot';
export { demoSnapshot } from './demo';
export {
  isStale,
  type Bar,
  type Quote,
  type SymbolInfo,
  type Resolution,
  type OrderRecord,
  type Position,
  type Account,
  type HoldingSide,
  type ConnectionStatus,
  type DataAdapter,
  type BrokerAdapter,
} from './contracts';
export {
  BrokerError,
  DataError,
  num,
  SerialQueue,
  RecordingAdapter,
  fixtureKey,
  type SerialQueueOptions,
  type FixtureMap,
  type RecordingAdapterOptions,
} from './adapters/index';
export {
  projectDeterministic,
  projectMonteCarlo,
  project,
  makeSeededRand,
  computeDrift,
  renderDriftMarkdown,
  recommendNextContribution,
  classifyDrift,
  classifySuccessBand,
  modifiedDietzReturn,
  annualiseReturn,
  realReturn,
  hasUsableYtdAnchor,
  type ProjectionInputs,
  type DeterministicResult,
  type MonteCarloResult,
  type ProjectionResult,
  type HoldingForDrift,
  type DriftBreach,
  type DriftReport,
  type HoldingForRebalance,
  type NextContributionInput,
  type BuyRecommendation,
  type NextContributionResult,
  type DriftState,
  type SuccessBand,
} from './analytics/index';
