import { ImageResponse } from 'next/og';

/**
 * Branded favicon — an amber "L" mark, so the browser tab / bookmarks show Lar
 * instead of the default globe. Generated by next/og (no static asset to manage).
 */
export const size = { width: 32, height: 32 };
export const contentType = 'image/png';

export default function Icon() {
  return new ImageResponse(
    <div
      style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: '#d98a2b',
        color: '#fff',
        fontSize: 22,
        fontWeight: 800,
        borderRadius: 7,
      }}
    >
      L
    </div>,
    { ...size },
  );
}
