/* Lar ← Málaga move sync. Run: node sync-move.mjs
   Reads the single source of truth (move-data.js) and regenerates the Move
   section of index.html — from the "── MOVE ──" comment marker through the
   section's closing tag — plus the moving-van hotspot's days-to-keys flavor
   text. Idempotent for a given data file and day. Mirrors sync-wealth.mjs. */
import { readFileSync, writeFileSync } from "node:fs";

const DATA = new URL("./move-data.js", import.meta.url).pathname;
const PAGE = new URL("./index.html", import.meta.url).pathname;

const w = {};
new Function("window", readFileSync(DATA, "utf8"))(w);
const D = w.MV_DATA;
if (!D) { console.error("MV_DATA not found in", DATA); process.exit(1); }

const esc = s => String(s)
  .replace(/&/g, "&amp;").replace(/"/g, "&quot;")
  .replace(/'/g, "&#39;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/* shortlist stickies — sheet gets "KIND|Title|Body|url?" via data-info */
const sticky = l => {
  const kind = `SHORTLIST ${l.id}`;
  const title = `${l.area} · ${l.price} · ${l.size}`;
  const body = `${l.detail} ${l.src}.`;
  const info = esc([kind, title, body, l.url || ""].join("|").replace(/\|$/, ""));
  return `            <div class="sticky" role="button" tabindex="0" data-info="${info}"><b>${l.id}</b><span class="lbl">${l.price} · ${l.size} · ${l.tag}</span><span class="note">${l.note}</span></div>`;
};

const meter = d => `              <div class="meter${d.full ? " full" : ""}" role="button" tabindex="0" data-date="${d.date}" data-info="${esc(d.info)}"><div class="name">${d.name}<small>${d.sub}</small></div><div class="trk"><span class="fill"></span></div><div class="val" data-out>—</div></div>`;

const S = D.meta.swept;
const huntInfo = esc([
  "THE HUNT", `Mijas Coast Board · swept ${D.meta.sweepDate}`,
  `${S.portals} portals swept, ${S.kept} genuine long-term finds kept, ${S.temporadaStripped} hidden temporada stripped, ${S.shortlisted} shortlisted, ${S.eyeballed} photo-verified. The full ranked board opens from here.`,
  D.meta.board,
].join("|"));
const briefInfo = esc([
  "THE BRIEF", `${D.brief.range.replace("k", "k")} · ${D.brief.corridor}`, D.brief.text,
].join("|"));

const section = `      <!-- ── MOVE (generated by sync-move.mjs from move-data.js — do not hand-edit) ── -->
      <section class="view" id="v-mv" aria-label="Move">
        <div class="paper">
          <div class="paper-top">
            <span class="crumb"><span class="dot">M</span>The Move<small>${D.keys.from} → ${D.keys.place} · dec 2026</small></span>
            <span class="board-title"><b>Move</b> · one countdown, four deadlines</span>
            <span class="crumb" role="button" tabindex="0" data-info="${huntInfo}"><span class="dot" style="background:var(--lime); color:var(--ink)">${D.shortlist.length}</span>on the board<small>sweep ${D.meta.sweepDate} · ${S.shortlisted} shortlisted</small></span>
          </div>
          <div class="board-grid">
            <div class="goal" role="button" tabindex="0" data-info="THE MOVE|Keys on ${D.keys.label}|${D.keys.place}, Costa del Sol. Everything on this board works backwards from this date — the money targets, the car sale, the rental hunt.">
              <div class="k">Keys in</div>
              <div class="g"><span id="mv-days">—</span> days</div>
              <div class="row"><span class="meta">${D.keys.label} · ${D.keys.place}</span><span class="badge-lime">ON TRACK</span></div>
              <div class="row"><span class="meta">Rental hunt live · ${D.brief.range} corridor</span></div>
            </div>
            <div class="workcard">
              <div class="wk-head"><h3>Deadlines</h3><span>days remaining · live</span></div>
${D.deadlines.map(meter).join("\n")}
            </div>
          </div>
          <div class="stickies" style="margin-top:16px">
${D.shortlist.map(sticky).join("\n")}
            <div class="sticky dark" role="button" tabindex="0" data-info="${briefInfo}"><b>${D.brief.range}</b><span class="lbl">The brief</span><span class="note">corridor · eyeballed · no temporada</span></div>
          </div>
        </div>
      </section>`;

let page = readFileSync(PAGE, "utf8");

/* replace from the MOVE marker through the section's close */
const start = page.search(/^\s*<!-- ── MOVE.*$/m);
if (start < 0) { console.error("MOVE marker not found"); process.exit(1); }
const end = page.indexOf("</section>", start);
if (end < 0) { console.error("MOVE </section> not found"); process.exit(1); }
page = page.slice(0, start) + section + page.slice(end + "</section>".length);

/* moving-van flavor text: refresh "N days to keys" */
const days = Math.max(0, Math.ceil((new Date(D.keys.date) - new Date()) / 86400000));
page = page.replace(/\d+ days to keys/g, `${days} days to keys`);

writeFileSync(PAGE, page);
console.log(`Move board synced — ${D.shortlist.length} shortlisted (${D.shortlist.filter(l => l.keeper).length} keepers), sweep ${D.meta.sweepDate}, ${days} days to keys.`);
